name: 'Ziti Webhook Action'
description: 'POST a Webhook over a Ziti network'
branding:
  icon: 'zap'  
  color: 'red'
inputs:
  ziti-id:
    description: 'Identity JSON for an enrolled Ziti endpoint'
    required: true
  webhook-url:
    description: 'URL for posting the payload'
    required: true
  webhook-secret:
    description: 'Secret for signature hash'
    required: true
  data:
    description: 'Arbitrary data to include in payload'
runs:
  using: 'node14'
  main: 'dist/index.js'
