name: mattermost-ziti-webhook
on: 
  create:
  delete:
  issues:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:
  pull_request:
  push:
  fork:
  release:
  workflow_dispatch:

jobs:
  mattermost-ziti-webhook:
    runs-on: ubuntu-latest
    name: POST Webhook
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ./  # uses self to surface any issues 
      with:
        ziti-id: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
        webhook-url: ${{ secrets.ZITI_MATTERMOST_WEBHOOK_URL }}
        webhook-secret: ${{ secrets.ZITI_MATTERMOSTI_WEBHOOK_SECRET }}
